version: "3.7"
services:
  api:
    build:
      args:
        user: david
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: ot-api
    container_name: ot-api
    restart: unless-stopped
    working_dir: /var/www/api/
    volumes:
      - ./:/var/www/api
    networks:
      - ot-challenge
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: ot-mongo
    restart: unless-stopped
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
    networks:
        - ot-challenge

  nginx:
    image: nginx:alpine
    container_name: ot-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/api
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ot-challenge

networks:
  ot-challenge:
    driver: bridge

volumes:
  ot-mysql:
    driver: local
